name:                ivector
version:             0.1.0.0
github:              "dcastrop/ivector"
license:             BSD3
author:              "David Castro-Perez"
maintainer:          "david.castro.dcp@gmail.com"
copyright:           "2017 David Castro-Perez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dcastrop/ivector#readme>

dependencies:
- base >= 4.7 && < 5
- singletons >= 2.4 && < 2.5
- ghc-typelits-natnormalise >= 0.6 && < 0.7
- ghc-typelits-knownnat >= 0.5 && < 0.6

library:
  source-dirs: src

tests:
  ivector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ivector
